### ISSUE TITLE
Tentang scp dan upload-serve di sisi irgsh-repo

### ISSUE THREAD

**Issue by herpiko** [BlankOn/irgsh-repo#2]
Pak @fajran, pak @aftian maaf mengganggu.

Saya dan teman-teman pengembang sedang berusaha mempelajari dan merekontruksi irgsh. Secara garis besar yang kami tangkap alur irgsh itu sebagai berikut :

`1. pemaket men-submit` ---> `2. irgsh-web` ---> `3. irgsh-node (builder)` ---> `4. irgsh-repo` ---> `5. reprepro` ---> `6. repository siap konsumsi`

Dari ketiga komponen utama irgsh, hanya irgsh-repo yang tidak kami temui dokumentasinya. Kami terkendala di nomor 5, yaitu : 

- Saat `builder` mencoba mengirim paket hasil build dengan dput (scp) ke `irgsh-node`, direktori khusus untuk build tersebut tidak dibuat secara otomatis di `incoming` (sisi irgsh-node), sehingga scp-nya gagal
- Saya mencoba membypass proses dput dengan scp langsung, namun 4 langkah terakhir untuk proses build tetap tidak tercapai (rebuild repo, rebuild repo done, repo log added, build log added)

Pertanyaan saya : 

- Apakah irgsh-repo yang menangani pembuatan direktori build di dalam incoming, sehingga dput dari builder bisa lancar masuk?
- Di sisi `irgsh-node`, di bawah `bin/`, ada `irgsh-upload-serve`, yang merujuk ke https://github.com/BlankOn/irgsh-repo/blob/master/irgsh_repo/serve.py
Apakah fungsi program tersebut? Apakah perlu dijalankan? Saya sudah mempelajari kodenya namun masih belum dapat memahami sepenuhnya, apakah seperti , `ORIGINAL_SSH_COMMAND="scp ..." ./bin/irgsh-upload-serve builder namabuilder` ?

Mohon petunjuknya.

**Comment by herpiko** [comment]
Ternyata dititip di ~/.ssh/authorized_keys. Kiriman dari irgsh-web ditangkap di sini.

![screen shot 2017-04-24 at 1 02 07 am](https://cloud.githubusercontent.com/assets/2534060/25316224/e4718d06-288c-11e7-868c-9cabf35ba664.png)

**Comment by tuanpembual** [comment]
horeeeeeeee
